# Generated by Django 5.2.6 on 2025-09-25 04:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bodega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('direccion', models.CharField(max_length=180)),
            ],
        ),
        migrations.CreateModel(
            name='EventoOutbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema', models.CharField(max_length=80)),
                ('clave', models.CharField(max_length=120)),
                ('carga', models.JSONField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('publicado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=40, unique=True)),
                ('nombre', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30)),
                ('nombre', models.CharField(blank=True, default='', max_length=80)),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ubicaciones', to='bodegaje.bodega')),
            ],
            options={
                'unique_together': {('bodega', 'codigo')},
            },
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('RETIRO', 'Retiro'), ('AJUSTE', 'Ajuste')], default='RETIRO', max_length=20)),
                ('lote', models.CharField(blank=True, max_length=40)),
                ('cantidad', models.IntegerField()),
                ('motivo', models.CharField(max_length=160)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bodegaje.producto')),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bodegaje.ubicacion')),
            ],
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lote', models.CharField(blank=True, max_length=40)),
                ('cantidad_disponible', models.IntegerField()),
                ('cantidad_reservada', models.IntegerField(default=0)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bodegaje.producto')),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bodegaje.ubicacion')),
            ],
            options={
                'indexes': [models.Index(fields=['ubicacion'], name='bodegaje_in_ubicaci_be198f_idx'), models.Index(fields=['producto', 'lote'], name='bodegaje_in_product_bcb967_idx')],
                'unique_together': {('producto', 'ubicacion', 'lote')},
            },
        ),
    ]
